# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c17f138020ca2c81431ebf84ab550dd3b376d2716906bc4c2b7207138d89b20f167de32a937aacf1bb917493085fb4fa557df4ea3f31d56aa774049da872e8b

test:
  secret_key_base: 782ff652261651ffe7ce360c57ae4a9088d6904a79b0350516dd0d9327d5bc11688fabfca8d4e3f33b8b2cd2a1dec900a38415633a6b6a7d6904aed95ec77544

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
